CREATE TABLE LEASE (
                       id BIGINT,
                       make VARCHAR(50),
                       model VARCHAR(100),
                       modelVariant VARCHAR(20),
                       year CHAR(5),
                       fuelType VARCHAR(50),
                       enginePower FLOAT,
                       engineSize FLOAT,
                       url VARCHAR(2048),
                       offer VARCHAR(255),
                       terms BOOLEAN,
                       confirmation BOOLEAN,
                       carValue NUMERIC(100, 10),
                       period INT,
                       downPayment NUMERIC(100, 10),
                       residualValuePercentage INT,
                       isEcoFriendly BOOLEAN,
                       monthlyPayment NUMERIC(100, 10),
                       PRIMARY KEY (id),
                       FOREIGN KEY (id) REFERENCES personal_information(id)
);